apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - image: vnfmsqkek3/auth-server:latest
        imagePullPolicy: Always
        name: auth-server
        ports:
            - containerPort: 80
              protocol: TCP
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: Always
        name: redis
        ports:
            - containerPort: 6379
              protocol: TCP