apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: stag
  region: ap-northeast-2

iam:
  withOIDC: true   
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true  

managedNodeGroups:
  - name: project4
    instanceType: t3.large
    minSize: 1
    maxSize: 1