apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: default
spec:
  selector:
    app: api-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80